[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  # Disable secrets scanning - we're using public env vars only
  SECRETS_SCAN_ENABLED = "false"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ignore false positive security warnings for documentation files
[build.processing]
  skip_processing = false

# Redirect rules for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Environment variable configuration
[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

